/// Definitions for vendor Ericsson, vendor value 193
use nom::IResult;
#[allow(unused_imports)]
use nom::number::streaming::{be_u64, be_u32, be_u16, be_u8};
#[allow(unused_imports)]
use std::net::{Ipv4Addr, Ipv6Addr};
use crate::radius::*;


pub fn parse(i: &[u8], typ: u8) -> IResult<&[u8], Attribute> {
    match typ {
		3 => map!{i, be_u32, |v| Attribute::VsaEricssonVigBalance(v)},
		4 => map!{i, be_u32, |v| Attribute::VsaEricssonVigCodec(v)},
		5 => value!(i, Attribute::VsaEricssonVigCurrency(i)),
		6 => value!(i, Attribute::VsaEricssonVigCurrencyQuote(i)),
		8 => map!{i, be_u32, |v| Attribute::VsaEricssonVigEndpointType(v)},
		9 => map!{i, be_u32, |v| Attribute::VsaEricssonVigSequenceNumber(v)},
		11 => map!{i, take!(4), |v:&[u8]| Attribute::VsaEricssonVigAccessAgentIpAddress(Ipv4Addr::new(v[0],v[1],v[2],v[3]))},
		12 => map!{i, be_u32, |v| Attribute::VsaEricssonVigQosClass(v)},
		14 => value!(i, Attribute::VsaEricssonVigDigestResponse(i)),
		15 => value!(i, Attribute::VsaEricssonVigDigestAttributes(i)),
		16 => value!(i, Attribute::VsaEricssonVigBusinessAgreementName(i)),
		17 => map!{i, be_u32, |v| Attribute::VsaEricssonVigCallRole(v)},
		20 => map!{i, take!(4), |v:&[u8]| Attribute::VsaEricssonVigRemoteSkUaIpAddress(Ipv4Addr::new(v[0],v[1],v[2],v[3]))},
		23 => value!(i, Attribute::VsaEricssonVigSite(i)),
		32 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTtlRelative(v)},
		33 => map!{i, be_u32, |v| Attribute::VsaEricssonVigAccountErrorReason(v)},
		34 => map!{i, be_u32, |v| Attribute::VsaEricssonVigLayerIdentity(v)},
		35 => map!{i, be_u32, |v| Attribute::VsaEricssonVigMajorProtocolVersion(v)},
		36 => map!{i, be_u32, |v| Attribute::VsaEricssonVigMinorProtocolVersion(v)},
		37 => map!{i, be_u32, |v| Attribute::VsaEricssonVigAuthenticationType(v)},
		38 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTrustedAccess(v)},
		39 => value!(i, Attribute::VsaEricssonVigUserName(i)),
		40 => value!(i, Attribute::VsaEricssonVigGlobalUniqueCallId(i)),
		41 => value!(i, Attribute::VsaEricssonVigGlobalUniqueServiceId(i)),
		42 => map!{i, be_u32, |v| Attribute::VsaEricssonVigInterimInterval(v)},
		43 => map!{i, be_u32, |v| Attribute::VsaEricssonVigAliveIndicator(v)},
		44 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTtlAbsolute(v)},
		45 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTtlStartEvent(v)},
		46 => map!{i, take!(4), |v:&[u8]| Attribute::VsaEricssonVigSkIpAddress(Ipv4Addr::new(v[0],v[1],v[2],v[3]))},
		47 => map!{i, take!(4), |v:&[u8]| Attribute::VsaEricssonVigUaIpAddress(Ipv4Addr::new(v[0],v[1],v[2],v[3]))},
		48 => map!{i, take!(4), |v:&[u8]| Attribute::VsaEricssonVigSaIpAddress(Ipv4Addr::new(v[0],v[1],v[2],v[3]))},
		49 => value!(i, Attribute::VsaEricssonVigCallingE164Number(i)),
		50 => value!(i, Attribute::VsaEricssonVigCallingH323Id(i)),
		51 => value!(i, Attribute::VsaEricssonVigCallingEmailAddress(i)),
		52 => value!(i, Attribute::VsaEricssonVigDialledE164Number(i)),
		53 => value!(i, Attribute::VsaEricssonVigDialledH323Id(i)),
		54 => value!(i, Attribute::VsaEricssonVigDialledEmailAddress(i)),
		55 => value!(i, Attribute::VsaEricssonVigRoutedE164Number(i)),
		56 => value!(i, Attribute::VsaEricssonVigRoutedH323Id(i)),
		57 => value!(i, Attribute::VsaEricssonVigRoutedEmailAddress(i)),
		58 => value!(i, Attribute::VsaEricssonVigSitekeeperName(i)),
		59 => value!(i, Attribute::VsaEricssonVigAccessGroupName(i)),
		60 => value!(i, Attribute::VsaEricssonVigAccessAgentName(i)),
		61 => value!(i, Attribute::VsaEricssonVigUserAgentGroupName(i)),
		62 => value!(i, Attribute::VsaEricssonVigUserAgentName(i)),
		63 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRoutingTariff(v)},
		64 => map!{i, be_u32, |v| Attribute::VsaEricssonVigReSelectionCounter(v)},
		65 => value!(i, Attribute::VsaEricssonVigCpnDigits(i)),
		66 => map!{i, be_u32, |v| Attribute::VsaEricssonVigCpnTon(v)},
		67 => map!{i, be_u32, |v| Attribute::VsaEricssonVigCpnNp(v)},
		68 => map!{i, be_u32, |v| Attribute::VsaEricssonVigCpnPi(v)},
		69 => map!{i, be_u32, |v| Attribute::VsaEricssonVigCpnSi(v)},
		70 => value!(i, Attribute::VsaEricssonVigDialledNumDigits(i)),
		71 => map!{i, be_u32, |v| Attribute::VsaEricssonVigDialledNumTon(v)},
		72 => map!{i, be_u32, |v| Attribute::VsaEricssonVigDialledNumNp(v)},
		73 => value!(i, Attribute::VsaEricssonVigRoutingNumDigits(i)),
		74 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRoutingNumTon(v)},
		75 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRoutingNumNp(v)},
		76 => value!(i, Attribute::VsaEricssonVigRedirectingNumDigits(i)),
		77 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRedirectingNumTon(v)},
		78 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRedirectingNumNp(v)},
		79 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRedirectingNumPi(v)},
		80 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRedirectingNumRfd(v)},
		81 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTimeStampUtc(v)},
		82 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTimeStampTz(v)},
		83 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTimeStampDst(v)},
		84 => map!{i, be_u32, |v| Attribute::VsaEricssonVigSessionRoutingDuration(v)},
		85 => map!{i, be_u32, |v| Attribute::VsaEricssonVigSessionRingingDuration(v)},
		86 => map!{i, be_u32, |v| Attribute::VsaEricssonVigAccessType(v)},
		87 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRequestedBandwidth(v)},
		88 => map!{i, be_u32, |v| Attribute::VsaEricssonVigAllowedBandwidth(v)},
		89 => map!{i, be_u32, |v| Attribute::VsaEricssonVigMediaChannelCount(v)},
		90 => value!(i, Attribute::VsaEricssonVigVoiceMediaRecForward(i)),
		91 => value!(i, Attribute::VsaEricssonVigVoiceMediaRecBackward(i)),
		92 => value!(i, Attribute::VsaEricssonVigVideoMediaRecForward(i)),
		93 => value!(i, Attribute::VsaEricssonVigVideoMediaRecBackward(i)),
		94 => value!(i, Attribute::VsaEricssonVigFaxMediaRecForward(i)),
		95 => value!(i, Attribute::VsaEricssonVigFaxMediaRecBackward(i)),
		96 => value!(i, Attribute::VsaEricssonVigDataMediaRecForward(i)),
		97 => value!(i, Attribute::VsaEricssonVigDataMediaRecBackward(i)),
		98 => map!{i, be_u32, |v| Attribute::VsaEricssonVigChargingCase(v)},
		99 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRelCauseCodingStd(v)},
		100 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRelCauseLocation(v)},
		101 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRelCauseClass(v)},
		102 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRelCauseValue(v)},
		103 => map!{i, be_u32, |v| Attribute::VsaEricssonVigRelReason(v)},
		104 => map!{i, be_u32, |v| Attribute::VsaEricssonVigInternalRelReasonVal(v)},
		105 => map!{i, be_u32, |v| Attribute::VsaEricssonVigInternalRelReasonOrig(v)},
		106 => map!{i, be_u32, |v| Attribute::VsaEricssonVigServiceId(v)},
		107 => value!(i, Attribute::VsaEricssonVigUserId(i)),
		108 => value!(i, Attribute::VsaEricssonVigServiceName(i)),
		109 => map!{i, be_u32, |v| Attribute::VsaEricssonVigTestCallIndicator(v)},
		110 => map!{i, be_u32, |v| Attribute::VsaEricssonVigEmergencyCallIndicator(v)},
		111 => value!(i, Attribute::VsaEricssonVigCallingId(i)),
		112 => value!(i, Attribute::VsaEricssonVigCalledId(i)),
		113 => value!(i, Attribute::VsaEricssonVigTranslatedId(i)),
		114 => value!(i, Attribute::VsaEricssonVigCallingUserGroupId(i)),
		115 => value!(i, Attribute::VsaEricssonVigCallingUsrSubGroupId(i)),
		116 => value!(i, Attribute::VsaEricssonVigCalledUsrGroupId(i)),
		117 => value!(i, Attribute::VsaEricssonVigCalledUsrSubGroupId(i)),
		118 => value!(i, Attribute::VsaEricssonVigTerminalType(i)),
		119 => map!{i, be_u32, |v| Attribute::VsaEricssonVigServiceDuration(v)},
		120 => map!{i, be_u32, |v| Attribute::VsaEricssonVigServiceExecutionResult(v)},
		121 => value!(i, Attribute::VsaEricssonVigServiceExeRsltDesc(i)),
		122 => value!(i, Attribute::VsaEricssonVigServiceDescription(i)),
		123 => value!(i, Attribute::VsaEricssonVigServiceSpecificInfo(i)),
		124 => map!{i, take!(4), |v:&[u8]| Attribute::VsaEricssonVigProxyIpAddress(Ipv4Addr::new(v[0],v[1],v[2],v[3]))},
		125 => map!{i, be_u32, |v| Attribute::VsaEricssonVigAuthDatarequest(v)},
		126 => map!{i, be_u32, |v| Attribute::VsaEricssonVigIptTimeStamp(v)},
		127 => map!{i, be_u32, |v| Attribute::VsaEricssonVigUserNameInfo(v)},
        _ => value!(i, Attribute::VsaUnknown(193, typ, i)),
    }
}
